### ISSUE TITLE
Add support for earlier versions of TFS

### ISSUE THREAD

**Issue by HolisticDeveloper** [ThatBlokeCalledJay/auto-app-version#4]
Could this be supported on, for example, TFS 2015?

**Comment by ThatBlokeCalledJay** [comment]
I'm afraid I don't plan on supporting TFS with this extension. That being said, it would be a bit dickish of me if I didn't investigate your request, so leave it with me and I'll do just that.

**Comment by HolisticDeveloper** [comment]
Thanks for considering it. I'm just getting started with building some .NET Core solutions with our TFS build system and this particular approach to versioning looks quite nice. 
I have done a bit more research since i opened this issue. TFS 2015 doesnt support the PAT approach to authentication so a different solution would be needed. At any rate, let me know your thoughts on it. I woukd be happy to contribute on it.

**Comment by ThatBlokeCalledJay** [comment]
@HolisticDeveloper this wouldn't really be a feature, more an entirely new extension/solution. I feel a little sad saying this but, it's not really something I'm going to invest time in. These extensions ultimately came about due to my own requirements, and I just decided to share them.  I'm going to close this off, but if you have any questions whilst developing your own solution, I would be happy to offer support where possible.
